### PR TITLE
Add morgan as logger middleware; fixes #1

### LINKED ISSUE #1: Add logging middleware for Express webapp
It would be nice to provide some HTTP level logging for our Express server. I've heard that [Morgan](https://github.com/expressjs/morgan) is a nice option for this.

### PR DESCRIPTION
**Pull request by dalwlad**
Add morgan loggind middleware.

### CODE REVIEW

**Comment by JamesMGreene** [comment]
:+1:

**Comment by gantoine** [comment]
👍

**Comment by JamesMGreene** [comment]
Ideally, you should try to include "Fixes #1" in your commit message for easy tracking and issue closure via PR merging.

You can update your local commit message with `git commit --amend` and then re-push it with `git push origin --force`, if you want to try doing this.

**Comment by anthonybrown** [comment]
👍

**Pull request closed without merging**
