### PR TITLE
Remove the 'X-Powered-By: Express' HTTP response header

### LINKED ISSUE #2: Don't send "Powered By Express" header with HTTP responses
By default, Express sends an X-Powered-By header that indicates that Express is the web server behind the request. Generally speaking, you don't want to allow evildoers to know specifically what technology is serving your page, to prevent targeted attacks.

Disable this response header by any means necessary. I think there's some middleware that does this? Maybe an Express configuration option?

### PR DESCRIPTION
**Pull request by JamesMGreene**
Fixes #2

### CODE REVIEW

**Comment by gantoine** [comment]
👍

**Comment by pertrai1** [comment]
👍

**Comment by JamesMGreene** [comment]
FYI, for those interested: http://expressjs.com/en/4x/api.html#app.set

**Comment by kwhinnery** [comment]
👍

**Comment by JamesMGreene** [comment]
As mentioned by someone in the room, we could have also used `app.disable` instead: http://expressjs.com/en/4x/api.html#app.disable

**Pull request merged**
